name:                haskell-lexer-parser-interpreter
version:             0.1.0.0
github:              "hazurl/haskell-lexer-parser-interpreter"
license:             MIT
author:              "Hazurl"
maintainer:          "jules.ricou.jr@gmail.com"
copyright:           "2018 Hazurl"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hazurl/haskell-lexer-parser-interpreter#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- utility-ht

library:
  source-dirs: src

executables:
  haskell-lexer-parser-interpreter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-lexer-parser-interpreter

tests:
  haskell-lexer-parser-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-lexer-parser-interpreter
